<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

namespace mod_projetvet\local;

use context_module;
use moodle_url;
use mod_projetvet\local\api\groups;

/**
 * Builds and validates notifications for tutor assignment changes.
 *
 * @package    mod_projetvet
 * @copyright  2026 Laurent David <laurent@call-learning.fr>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class assignment_notifications {
    /** First assignment scenario. */
    public const SCENARIO_FIRST = 'first_assignment';

    /** Definitive tutor change scenario. */
    public const SCENARIO_DEFINITIVE = 'definitive_change';

    /** Temporary substitution start scenario. */
    public const SCENARIO_TEMPORARY_START = 'temporary_start';

    /** Temporary substitution end scenario. */
    public const SCENARIO_TEMPORARY_END = 'temporary_end';

    /**
     * Sign an assignment transition so the confirmation request cannot forge it.
     *
     * @param int $cmid Course module id.
     * @param int $projetvetid ProjetVet instance id.
     * @param int $studentid Student id.
     * @param int $beforeprimaryid Previous principal tutor.
     * @param int $afterprimaryid New principal tutor.
     * @param int $beforetemporaryid Previous temporary tutor.
     * @param int $aftertemporaryid New temporary tutor.
     * @param int $date Effective date.
     * @return string
     */
    public static function sign_change(
        int $cmid,
        int $projetvetid,
        int $studentid,
        int $beforeprimaryid,
        int $afterprimaryid,
        int $beforetemporaryid,
        int $aftertemporaryid,
        int $date
    ): string {
        global $CFG;

        $payload = implode(':', [
            $cmid,
            $projetvetid,
            $studentid,
            $beforeprimaryid,
            $afterprimaryid,
            $beforetemporaryid,
            $aftertemporaryid,
            $date,
        ]);
        $key = $CFG->passwordsaltmain ?? get_site_identifier();
        return hash_hmac('sha256', $payload, $key);
    }

    /**
     * Verify a signed assignment transition.
     *
     * @param string $signature Signature generated by {@see self::sign_change()}.
     * @param int $cmid Course module id.
     * @param int $projetvetid ProjetVet instance id.
     * @param int $studentid Student id.
     * @param int $beforeprimaryid Previous principal tutor.
     * @param int $afterprimaryid New principal tutor.
     * @param int $beforetemporaryid Previous temporary tutor.
     * @param int $aftertemporaryid New temporary tutor.
     * @param int $date Effective date.
     * @return bool
     */
    public static function is_valid_signature(
        string $signature,
        int $cmid,
        int $projetvetid,
        int $studentid,
        int $beforeprimaryid,
        int $afterprimaryid,
        int $beforetemporaryid,
        int $aftertemporaryid,
        int $date
    ): bool {
        return hash_equals(
            self::sign_change(
                $cmid,
                $projetvetid,
                $studentid,
                $beforeprimaryid,
                $afterprimaryid,
                $beforetemporaryid,
                $aftertemporaryid,
                $date
            ),
            $signature
        );
    }

    /**
     * Detect the business scenario from the assignment state transition.
     *
     * @param int $beforeprimaryid Previous principal tutor, or 0.
     * @param int $afterprimaryid New principal tutor, or 0.
     * @param int $beforetemporaryid Previous temporary tutor, or 0.
     * @param int $aftertemporaryid New temporary tutor, or 0.
     * @return string
     */
    public static function detect_scenario(
        int $beforeprimaryid,
        int $afterprimaryid,
        int $beforetemporaryid = 0,
        int $aftertemporaryid = 0
    ): string {
        if (!$beforeprimaryid && $afterprimaryid && !$beforetemporaryid && !$aftertemporaryid) {
            return self::SCENARIO_FIRST;
        }

        if (
            $beforeprimaryid && $afterprimaryid && $beforeprimaryid !== $afterprimaryid
                && !$beforetemporaryid && !$aftertemporaryid
        ) {
            return self::SCENARIO_DEFINITIVE;
        }

        if ($beforeprimaryid && $afterprimaryid && !$beforetemporaryid && $aftertemporaryid) {
            return self::SCENARIO_TEMPORARY_START;
        }

        if ($beforeprimaryid && $afterprimaryid && $beforetemporaryid && !$aftertemporaryid) {
            return self::SCENARIO_TEMPORARY_END;
        }

        throw new \invalid_parameter_exception('Invalid tutor assignment notification state.');
    }

    /**
     * Validate that the state belongs to the given ProjetVet activity.
     *
     * @param int $cmid Course module id.
     * @param int $projetvetid ProjetVet instance id.
     * @param int $studentid Student id.
     * @param int[] $tutorids Tutor ids to validate.
     * @return void
     */
    public static function validate_context(
        int $cmid,
        int $projetvetid,
        int $studentid,
        array $tutorids
    ): void {
        $cm = get_coursemodule_from_id('projetvet', $cmid, 0, false, MUST_EXIST);
        context_module::instance($cm->id);
        if ((int) $cm->instance !== $projetvetid) {
            throw new \invalid_parameter_exception('The ProjetVet instance does not match the course module.');
        }

        $studentids = array_map('intval', array_column(groups::get_all_students($cmid), 'uniqueid'));
        if (!in_array($studentid, $studentids, true)) {
            throw new \invalid_parameter_exception('The selected user is not an eligible student.');
        }

        $eligibleteachers = array_map('intval', groups::get_all_teachers($cmid));
        foreach (array_unique(array_filter(array_map('intval', $tutorids))) as $tutorid) {
            if (!in_array($tutorid, $eligibleteachers, true)) {
                throw new \invalid_parameter_exception('The selected user is not an eligible teacher.');
            }
        }
    }

    /**
     * Build the per-recipient message plan.
     *
     * @param int $cmid Course module id.
     * @param int $projetvetid ProjetVet instance id.
     * @param int $studentid Student id.
     * @param int $beforeprimaryid Previous principal tutor, or 0.
     * @param int $afterprimaryid New principal tutor, or 0.
     * @param int $beforetemporaryid Previous temporary tutor, or 0.
     * @param int $aftertemporaryid New temporary tutor, or 0.
     * @param int $date Effective date.
     * @return array{scenario: string, messages: array}
     */
    public static function build_plan(
        int $cmid,
        int $projetvetid,
        int $studentid,
        int $beforeprimaryid,
        int $afterprimaryid,
        int $beforetemporaryid = 0,
        int $aftertemporaryid = 0,
        int $date = 0
    ): array {
        $scenario = self::detect_scenario(
            $beforeprimaryid,
            $afterprimaryid,
            $beforetemporaryid,
            $aftertemporaryid
        );
        self::validate_context(
            $cmid,
            $projetvetid,
            $studentid,
            [$beforeprimaryid, $afterprimaryid, $beforetemporaryid, $aftertemporaryid]
        );

        $student = \core_user::get_user($studentid, '*', MUST_EXIST);
        $userids = array_unique(array_filter([
            $beforeprimaryid,
            $afterprimaryid,
            $beforetemporaryid,
            $aftertemporaryid,
        ]));
        $users = [];
        foreach ($userids as $userid) {
            $users[$userid] = \core_user::get_user($userid, '*', MUST_EXIST);
        }

        $link = (new moodle_url('/mod/projetvet/view.php', ['id' => $cmid, 'studentid' => $studentid]))->out(false);
        $date = $date ?: time();
        $primarytutorid = $afterprimaryid ?: $beforeprimaryid;
        $newtutorid = in_array($scenario, [self::SCENARIO_TEMPORARY_START, self::SCENARIO_TEMPORARY_END], true)
            ? ($aftertemporaryid ?: $beforetemporaryid)
            : $afterprimaryid;
        $data = [
            'studentfirstname' => $student->firstname,
            'studentlastname' => $student->lastname,
            'primarytutorfirstname' => $users[$primarytutorid]->firstname ?? '',
            'primarytutorlastname' => $users[$primarytutorid]->lastname ?? '',
            'formertutorfirstname' => $users[$beforeprimaryid]->firstname ?? '',
            'formertutorlastname' => $users[$beforeprimaryid]->lastname ?? '',
            'newtutorfirstname' => $users[$newtutorid]->firstname ?? '',
            'newtutorlastname' => $users[$newtutorid]->lastname ?? '',
            'date' => userdate($date, get_string('strftimedatefullshort', 'langconfig')),
            'link' => $link,
        ];
        $bodydata = $data;
        foreach (
            ['studentfirstname', 'studentlastname', 'primarytutorfirstname', 'primarytutorlastname',
            'formertutorfirstname', 'formertutorlastname', 'newtutorfirstname', 'newtutorlastname'] as $key
        ) {
            $bodydata[$key] = s($bodydata[$key]);
        }

        $roles = match ($scenario) {
            self::SCENARIO_FIRST => [
                [
                    'userid' => $studentid,
                    'subjectkey' => 'assignment_first_student_subject',
                    'bodykey' => 'assignment_first_student_body',
                ],
                [
                    'userid' => $afterprimaryid,
                    'subjectkey' => 'assignment_first_tutor_subject',
                    'bodykey' => 'assignment_first_tutor_body',
                ],
            ],
            self::SCENARIO_DEFINITIVE => [
                [
                    'userid' => $studentid,
                    'subjectkey' => 'assignment_definitive_student_subject',
                    'bodykey' => 'assignment_definitive_student_body',
                ],
                [
                    'userid' => $beforeprimaryid,
                    'subjectkey' => 'assignment_definitive_former_subject',
                    'bodykey' => 'assignment_definitive_former_body',
                ],
                [
                    'userid' => $afterprimaryid,
                    'subjectkey' => 'assignment_definitive_new_subject',
                    'bodykey' => 'assignment_definitive_new_body',
                ],
            ],
            self::SCENARIO_TEMPORARY_START => [
                [
                    'userid' => $studentid,
                    'subjectkey' => 'assignment_temporary_start_student_subject',
                    'bodykey' => 'assignment_temporary_start_student_body',
                ],
                [
                    'userid' => $beforeprimaryid,
                    'subjectkey' => 'assignment_temporary_start_primary_subject',
                    'bodykey' => 'assignment_temporary_start_primary_body',
                ],
                [
                    'userid' => $aftertemporaryid,
                    'subjectkey' => 'assignment_temporary_start_temporary_subject',
                    'bodykey' => 'assignment_temporary_start_temporary_body',
                ],
            ],
            self::SCENARIO_TEMPORARY_END => [
                [
                    'userid' => $studentid,
                    'subjectkey' => 'assignment_temporary_end_student_subject',
                    'bodykey' => 'assignment_temporary_end_student_body',
                ],
                [
                    'userid' => $beforeprimaryid,
                    'subjectkey' => 'assignment_temporary_end_primary_subject',
                    'bodykey' => 'assignment_temporary_end_primary_body',
                ],
                [
                    'userid' => $beforetemporaryid,
                    'subjectkey' => 'assignment_temporary_end_temporary_subject',
                    'bodykey' => 'assignment_temporary_end_temporary_body',
                ],
            ],
        };

        return [
            'scenario' => $scenario,
            'messages' => array_map(function (array $role) use ($data, $bodydata): array {
                return $role + ['data' => $data, 'bodydata' => $bodydata];
            }, $roles),
        ];
    }
}
